// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateUser implements createUser operation.
//
// Create a user.
//
// POST /api/v1/users
func (UnimplementedHandler) CreateUser(ctx context.Context, req *CreateUserReq) (r *CreateUser, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUser implements getUser operation.
//
// Get user by ID.
//
// GET /api/v1/users/{userID}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// Get all users.
//
// GET /api/v1/users
func (UnimplementedHandler) GetUsers(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// Ping API.
//
// GET /api/v1/ping
func (UnimplementedHandler) Ping(ctx context.Context) (r PingOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
