// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateMessageOperation             OperationName = "CreateMessage"
	DeleteMyDirectionalIntentOperation OperationName = "DeleteMyDirectionalIntent"
	DeleteSwapIntentOperation          OperationName = "DeleteSwapIntent"
	GetMessagesOperation               OperationName = "GetMessages"
	GetRoomOperation                   OperationName = "GetRoom"
	JoinRoomOperation                  OperationName = "JoinRoom"
	PatchMyDirectionalIntentOperation  OperationName = "PatchMyDirectionalIntent"
	PingOperation                      OperationName = "Ping"
	PutConnectionOperation             OperationName = "PutConnection"
	SubscribeRoomStreamOperation       OperationName = "SubscribeRoomStream"
)
