// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateMessage implements createMessage operation.
	//
	// Send message to adjacent player.
	//
	// POST /api/rooms/{room_id}/messages
	CreateMessage(ctx context.Context, req *CreateMessageRequest, params CreateMessageParams) (*Message, error)
	// DeleteMyDirectionalIntent implements deleteMyDirectionalIntent operation.
	//
	// Set directional swap intent OFF (prev or next).
	//
	// DELETE /api/rooms/{room_id}/players/me/intent
	DeleteMyDirectionalIntent(ctx context.Context, req *DirectionalIntentRequest, params DeleteMyDirectionalIntentParams) (*DirectionalIntentResponse, error)
	// DeleteSwapIntent implements deleteSwapIntent operation.
	//
	// Cancel swap intent by target player ID.
	//
	// DELETE /api/rooms/{room_id}/swaps/intents/{target_player_id}
	DeleteSwapIntent(ctx context.Context, params DeleteSwapIntentParams) (*DeleteSwapIntentResponse, error)
	// GetMessages implements getMessages operation.
	//
	// Get message history related to myself.
	//
	// GET /api/rooms/{room_id}/messages
	GetMessages(ctx context.Context, params GetMessagesParams) ([]Message, error)
	// GetRoom implements getRoom operation.
	//
	// Get room state.
	//
	// GET /api/rooms/{room_id}
	GetRoom(ctx context.Context, params GetRoomParams) (*RoomStateResponse, error)
	// GetRoomIntersections implements getRoomIntersections operation.
	//
	// Get intersecting edge pairs in room.
	//
	// GET /api/rooms/{room_id}/intersections
	GetRoomIntersections(ctx context.Context, params GetRoomIntersectionsParams) (*RoomIntersectionsResponse, error)
	// JoinRoom implements joinRoom operation.
	//
	// Join matching queue.
	//
	// POST /api/rooms/join
	JoinRoom(ctx context.Context, req *JoinRoomRequest) (*JoinRoomResponse, error)
	// PatchMyDirectionalIntent implements patchMyDirectionalIntent operation.
	//
	// Set directional swap intent ON (prev or next).
	//
	// PATCH /api/rooms/{room_id}/players/me/intent
	PatchMyDirectionalIntent(ctx context.Context, req *DirectionalIntentRequest, params PatchMyDirectionalIntentParams) (*DirectionalIntentResponse, error)
	// Ping implements ping operation.
	//
	// Ping.
	//
	// GET /api/v1/ping
	Ping(ctx context.Context) (PingOK, error)
	// PutConnection implements putConnection operation.
	//
	// Upsert connection intent by target player ID.
	//
	// PUT /api/rooms/{room_id}/connections/{target_id}
	PutConnection(ctx context.Context, req *ConnectionRequest, params PutConnectionParams) (*ConnectionResponse, error)
	// SubscribeRoomStream implements subscribeRoomStream operation.
	//
	// Subscribe room events (SSE).
	//
	// GET /api/rooms/{room_id}/stream
	SubscribeRoomStream(ctx context.Context, params SubscribeRoomStreamParams) (SubscribeRoomStreamOK, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
